### PR TITLE
Fix building on MSYS2 MINGW64

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tgalaj** [comment]
Is `bz2` library really necessary to build this project on MSYS2? I've never encountered that this lib is needed to build this project.

**Comment by ghost** [comment]
It could be because some libraries used by your project were configured differently on MSYS2 MINGW64 with bz2 support on so bz2 must be linked to satisfy the linker.

**Comment by ghost** [comment]
You could try to wrap this line on CMakeLists.txt with `if(MinGW)`. Note: the variable `MinGW` is also defined for standalone MinGW, but I have no idea how to accurately check for just MSYS2 MINGW64 so it's the best I know.

**Comment by tgalaj** [comment]
Thanks for your contribution @iahung !

**Pull request merged**
